/*
Problem 1: Multiples of 3 and 5

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below the provided parameter value number.
*/
int problem1(int n){
  int sum = 0;
  for(int i = 2; i < n; i++){
    if(i % 3 == 0 || i % 5 == 0){
      sum += i;
    }
  }
  return sum;
}


/*
Project Euler: Problem 2: Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.
*/
int problem2(int n){
  if(n == 1) return 1;
  if(n == 2) return 2;
  int arr[n];
  arr[0] = 1;
  arr[1] = 2;

  int sum = 2;

  for(int i = 2; i < n; i++){
    arr[i] = arr[i-1] + arr[i-2];
    if(arr[i] % 2 == 0) sum+= arr[i];
  }
  printarr(arr, n);
  return sum;
}